### ISSUE TITLE
[1.16.5] Removes boss pokemon even with filter

### ISSUE THREAD

**Issue by MrDefined** [Daniel-Forge-Development/PokeRemoval#4]
Current filter in the config:
![image](https://user-images.githubusercontent.com/13711377/179620578-36bf573f-bc39-4a41-a95a-7544e695ca67.png)

Just received a ticket from a player telling us a boss spawned, then despawned when the message showing clearing pokemon
![image](https://user-images.githubusercontent.com/13711377/179620711-b443323c-e738-45a6-a305-21758fc2755f.png)

Tested this by spawning in a boss and waiting for the clear, and it indeed cleared the boss pokemon

**Comment by danorris709** [comment]
Your config is incorrect. The specs should be on the same line
